export const SPRITE_MANIFEST = Object.freeze({
  room: 'room.png',
  rug: 'rug.png',
  window: 'window.png',
  tv: 'tv.png',
  robot: 'robot.png',
  dock: 'dock.png',
  dock_half: 'dock_half.png',
  dock_full: 'dock_full.png',
  tv_show1: 'tv_show1.jpg',
  tv_show2: 'tv_show2.jpg',
  tv_show3: 'tv_show3.jpg',
  underside: 'underside.png',
  mop_pads: 'mop_pads.png',
  icon_vacuum: 'icon_vacuum.png',
  icon_mop: 'icon_mop.png',
  icon_dirty: 'icon_dirty.png',
  icon_dust: 'icon_dust.png',
  icon_water: 'icon_water.png',
  couch: 'couch.png',
  table: 'table.png',
  plant: 'plant.png',
  toybox: 'toybox.png',
  catbed: 'catbed.png',
  basket: 'basket.png',
  sparkle: 'sparkle.png',
  dog_sit: 'dog_sit.png',
  dog_walk: 'dog_walk.png',
  dog_sleep: 'dog_sleep.png',
  cat_sit: 'cat_sit.png',
  cat_walk: 'cat_walk.png',
  cat_sleep: 'cat_sleep.png',
  poop: 'poop.png',
  dustbunny: 'dustbunny.png',
  crumbs: 'crumbs.png',
  cereal: 'cereal.png',
  leaf: 'leaf.png',
  sock: 'sock.png',
  toy_ball: 'toy_ball.png',
  toy_block: 'toy_block.png',
  disco_ball: 'disco_ball.png',
});

export const VOICE_LINES = Object.freeze([
  'start_clean',
  'go_charge',
  'charge_done',
  'go_empty',
  'emptying',
  'go_dock',
  'uh_oh',
  'go_mop_install',
  'mop_installed',
  'go_mop_wash',
  'washing',
  'mop_done',
  'remove_pads',
  'bag_full',
  'clean_empty',
  'dirty_full',
  'thank_you',
]);
