import { publicAssetUrl } from './assetUrl.js';
import { SFX_CLIPS } from './assetManifest.js';

// Recorded sound effects (ElevenLabs, generated by scripts/gen_sfx.py),
// played through the SoundEngine master so the mute button applies.
// play() returns false when a clip isn't available — callers keep a synth
// fallback so the game still sounds right without the asset pack.
export class Sfx {
  constructor(sound) {
    this.sound = sound;
    this.raw = {};      // name -> ArrayBuffer (fetched)
    this.buffers = {};  // name -> AudioBuffer (decoded once ctx exists)
    this.load();
  }

  async load() {
    await Promise.all(SFX_CLIPS.map(async (name) => {
      try {
        const res = await fetch(publicAssetUrl(`assets/sfx/${name}.mp3`));
        if (res.ok) this.raw[name] = await res.arrayBuffer();
      } catch (e) { /* clip pack missing — synth fallbacks cover it */ }
    }));
  }

  play(name, { vol = 0.9, rate = 1, jitter = 0.07 } = {}) {
    const s = this.sound;
    if (!s.ctx || s.muted) return true; // muted counts as handled — no fallback beep
    const start = (buf) => {
      const src = s.ctx.createBufferSource();
      src.buffer = buf;
      src.playbackRate.value = rate * (1 + (Math.random() * 2 - 1) * jitter);
      const g = s.ctx.createGain();
      g.gain.value = vol;
      src.connect(g);
      g.connect(s.master);
      src.start();
    };
    if (this.buffers[name]) {
      start(this.buffers[name]);
      return true;
    }
    if (this.raw[name]) {
      s.ctx.decodeAudioData(this.raw[name].slice(0)).then((buf) => {
        this.buffers[name] = buf;
        start(buf);
      }).catch(() => {});
      return true;
    }
    return false;
  }
}
